// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relay.Api.Data;

#nullable disable

namespace Relay.Api.Data.Migrations
{
    [DbContext(typeof(RelayDbContext))]
    [Migration("20260814010511_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Relay.Api.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("industry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("timezone");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Relay.Api.Data.Entities.ActivityEvent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("event_type");

                    b.Property<DateOnly?>("LocalWeekStart")
                        .HasColumnType("date")
                        .HasColumnName("local_week_start");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("location");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("occurred_at");

                    b.Property<DateOnly?>("OccurredLocalDate")
                        .HasColumnType("date")
                        .HasColumnName("occurred_local_date");

                    b.Property<string>("Outcome")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("outcome");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "LocalWeekStart")
                        .HasDatabaseName("IX_activity_events_account_local_week");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AccountId", "LocalWeekStart"), new[] { "Location", "EventType" });

                    b.HasIndex("AccountId", "Location", "EventType", "OccurredAt")
                        .HasDatabaseName("IX_activity_events_dedup");

                    b.ToTable("activity_events", (string)null);
                });

            modelBuilder.Entity("Relay.Api.Data.Entities.SeedRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountRows")
                        .HasColumnType("int")
                        .HasColumnName("account_rows");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("applied_at_utc");

                    b.Property<int>("EventRows")
                        .HasColumnType("int")
                        .HasColumnName("event_rows");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("source_file");

                    b.HasKey("Id");

                    b.ToTable("seed_runs", (string)null);
                });

            modelBuilder.Entity("Relay.Api.Data.Entities.ActivityEvent", b =>
                {
                    b.HasOne("Relay.Api.Data.Entities.Account", "Account")
                        .WithMany("Events")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Relay.Api.Data.Entities.Account", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
